import { Platform, StatusBar, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fbfbfa', paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 },
  header: { paddingHorizontal: 18, paddingTop: 10, paddingBottom: 14, borderBottomWidth: 1, borderBottomColor: '#e8e6e2', backgroundColor: '#fbfbfa' },
  headerTop: { minHeight: 30, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  version: { color: '#6b6b6b', fontSize: 12, fontWeight: '700' },
  backBtn: { paddingVertical: 6, paddingRight: 12 },
  backText: { fontSize: 15, fontWeight: '700', color: '#2b2b2b' },
  headerTitle: { fontSize: 28, lineHeight: 34, fontWeight: '800', color: '#1e1e1e', marginTop: 4 },
  headerSub: { fontSize: 13, color: '#6b6b6b', marginTop: 4, lineHeight: 18 },
  searchTop: { borderWidth: 1, borderColor: '#e1ded8', backgroundColor: '#fff', borderRadius: 999, paddingHorizontal: 12, paddingVertical: 7 },
  searchTopText: { fontSize: 12, fontWeight: '800', color: '#2b2b2b' },
  content: { padding: 16, paddingBottom: 48 },
  notice: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8e6e2', borderRadius: 18, padding: 14, marginBottom: 12 },
  noticeTitle: { fontWeight: '900', fontSize: 13, textTransform: 'uppercase', letterSpacing: .4, color: '#3c3c3c' },
  noticeText: { color: '#6b6b6b', marginTop: 6, lineHeight: 19 },
  threadCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8e6e2', borderTopWidth: 4, borderRadius: 20, padding: 15, marginBottom: 13 },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  badge: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  badgeText: { fontSize: 16, fontWeight: '800' },
  cardTitle: { fontSize: 18, fontWeight: '800', color: '#1e1e1e' },
  cardSub: { fontSize: 12, color: '#6b6b6b', marginTop: 2 },
  cardDesc: { fontSize: 13, color: '#444', lineHeight: 19, marginTop: 4 },
  actionRow: { flexDirection: 'row', gap: 10, marginTop: 13 },
  primary: { paddingHorizontal: 14, paddingVertical: 11, borderRadius: 13 },
  primaryText: { color: '#fff', fontWeight: '800' },
  secondary: { paddingHorizontal: 14, paddingVertical: 11, borderRadius: 13, borderWidth: 1, borderColor: '#e8e6e2', backgroundColor: '#fff' },
  secondaryText: { color: '#2b2b2b', fontWeight: '800' },
  panel: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8e6e2', borderTopWidth: 4, borderRadius: 18, padding: 15, marginBottom: 16 },
  panelSoft: { backgroundColor: '#faf9f7', borderWidth: 1, borderColor: '#e8e6e2', borderRadius: 18, padding: 14, marginBottom: 14 },
  sectionLabel: { fontSize: 12, fontWeight: '900', textTransform: 'uppercase', letterSpacing: .4, marginBottom: 8, color: '#3c3c3c' },
  bodyText: { fontSize: 15, lineHeight: 22, color: '#2a2a2a', marginBottom: 10 },
  bigLabel: { fontSize: 12, color: '#3c3c3c', fontWeight: '900', textTransform: 'uppercase', letterSpacing: .4, marginTop: 10, marginBottom: 8 },
  listItem: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8e6e2', borderRadius: 16, padding: 13, marginBottom: 9 },
  anchorItem: { backgroundColor: '#faf9f7', borderWidth: 1, borderColor: '#e8e6e2', borderRadius: 16, padding: 13, marginBottom: 8 },
  readingItem: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8e6e2', borderRadius: 16, padding: 13, marginBottom: 8 },
  kicker: { fontSize: 12, fontWeight: '900', color: '#333', marginBottom: 4 },
  listTitle: { fontSize: 15, fontWeight: '800', color: '#1e1e1e', lineHeight: 20 },
  listMeta: { fontSize: 12, color: '#6b6b6b', lineHeight: 17, marginTop: 3 },
  segmentNav: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  dotButton: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8e6e2' },
  dotText: { fontSize: 12, fontWeight: '800', color: '#444' },
  segmentCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8e6e2', borderTopWidth: 4, borderRadius: 20, padding: 15, marginBottom: 12 },
  segmentTitle: { fontSize: 21, lineHeight: 27, fontWeight: '900', color: '#1e1e1e', marginBottom: 10 },
  pill: { backgroundColor: '#faf9f7', borderWidth: 1, borderColor: '#e1ded8', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  pillText: { fontSize: 12, fontWeight: '800', color: '#3a3a3a' },
  verseCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8e6e2', borderLeftWidth: 4, borderRadius: 16, padding: 13, marginBottom: 9 },
  verseRef: { fontSize: 13, fontWeight: '900', color: '#1e1e1e' },
  verseText: { fontSize: 13, color: '#555', lineHeight: 18, marginTop: 4 },
  expanded: { marginTop: 9, paddingTop: 9, borderTopWidth: 1, borderTopColor: '#e8e6e2' },
  expandedText: { fontSize: 13, lineHeight: 19, color: '#333', marginBottom: 6 },
  bold: { fontWeight: '900' },
  prompt: { fontSize: 14, lineHeight: 21, color: '#333', marginBottom: 7 },
  bottomNav: { flexDirection: 'row', gap: 10, marginTop: 18 },
  navBtn: { flex: 1, paddingVertical: 13, borderRadius: 14, backgroundColor: '#2b2b2b', alignItems: 'center' },
  navText: { color: '#fff', fontWeight: '900' },
  disabled: { opacity: .35 },
  searchWrap: { padding: 16, borderBottomWidth: 1, borderBottomColor: '#e8e6e2' },
  searchInput: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e8e6e2', borderRadius: 16, paddingHorizontal: 14, paddingVertical: 13, fontSize: 16 },
  emptyText: { fontSize: 14, color: '#6b6b6b', lineHeight: 20, padding: 12 }
});
